# Generated by Django 5.0.1 on 2025-10-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_questionsource_questiontypeconfig_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exampattern",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Exam Pattern",
                "verbose_name_plural": "Exam Patterns",
            },
        ),
        migrations.AddField(
            model_name="exampattern",
            name="ai_prompt",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="exampattern",
            name="class_name",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="exampattern",
            name="pattern_source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Creation"),
                    ("ai_generated", "AI Generated"),
                    ("imported", "Imported"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="exampattern",
            name="subject",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="exampattern",
            name="total_marks",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="exampattern",
            name="total_questions",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="exampattern",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
