# Generated by Django 5.0.1 on 2025-10-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_exampattern_options_exampattern_ai_prompt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionpaper",
            name="edited_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="questionpaper",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
