# Generated by Django 5.0.1 on 2025-11-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionpaper",
            name="cost",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
    ]
