# Generated by Django 5.0.1 on 2025-11-05 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_questionpaper_cost"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(max_length=10)),
                ("subject", models.CharField(max_length=50)),
                ("chapter", models.CharField(blank=True, max_length=50, null=True)),
                ("question_text", models.TextField()),
                ("question_hash", models.CharField(db_index=True, max_length=64)),
                ("embedding", models.JSONField(blank=True, null=True)),
                ("question_type", models.CharField(blank=True, max_length=50)),
                ("marks", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "paper_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_questions",
                        to="core.questionpaper",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["class_name", "subject", "chapter"],
                        name="core_genera_class_n_ead350_idx",
                    ),
                    models.Index(
                        fields=["question_hash"], name="core_genera_questio_d0af04_idx"
                    ),
                ],
            },
        ),
    ]
