# Generated by Django 5.2.11 on 2026-02-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_generatedquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('textbook', 'Textbook'), ('notes', 'Notes'), ('bank', 'Question Bank'), ('syllabus', 'Syllabus'), ('reference', 'Reference Book')], max_length=50),
        ),
    ]
