# Generated by Django 5.2.11 on 2026-02-06 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_material_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examblueprint',
            options={'ordering': ['class_name', 'subject']},
        ),
        migrations.RemoveField(
            model_name='examblueprint',
            name='section',
        ),
    ]
