# Generated by Django 5.2.14 on 2026-06-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="exampattern",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("generating", "Generating"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                ],
                default="done",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="exampattern",
            name="task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="exampattern",
            name="pattern_source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Creation"),
                    ("ai_generated", "AI Generated"),
                    ("imported", "Imported"),
                    ("cbse_official", "CBSE Official"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
