# Generated by Django 5.2.14 on 2026-06-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_exampattern_status_taskid"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionpaper",
            name="paper_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
