# Generated by Django 5.2.14 on 2026-06-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_add_paper_data_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="total_cost_accumulated",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="school",
            name="total_papers_generated",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="school",
            name="total_tokens_used",
            field=models.BigIntegerField(default=0),
        ),
    ]
