# Generated by Django 5.2.14 on 2026-06-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_userprofile_allowed_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="exampattern",
            name="sqp_year",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
