# Generated by Django 5.2.14 on 2026-06-23 11:59
#
# Hand-edited to tolerate schema drift: the three legacy models below were never created
# in some databases (their migration history drifted from the actual schema), so the
# original auto-generated AlterUniqueTogether / DeleteModel operations failed with
# "Found wrong number (0) of constraints …". We now update Django's STATE and drop the
# tables only IF they exist, which works whether or not the tables are present.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_add_sqp_year_to_exampattern"),
    ]

    operations = [
        # Choices-only change on an existing CharField — no DB-level change on SQLite.
        migrations.AlterField(
            model_name="exampattern",
            name="pattern_source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Creation"),
                    ("ai_generated", "AI Generated"),
                    ("imported", "Imported"),
                    ("cbse_official", "CBSE Official"),
                    ("one_mark_test", "One Mark Test"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        # Remove three legacy/unused models. Split state from DB so the (possibly absent)
        # tables don't break the migration.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name="detailedblueprinttemplate",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="detailedblueprinttemplate",
                    name="created_by",
                ),
                migrations.DeleteModel(name="QuestionSource"),
                migrations.DeleteModel(name="QuestionTypeConfig"),
                migrations.DeleteModel(name="DetailedBlueprintTemplate"),
            ],
            database_operations=[
                migrations.RunSQL(
                    "DROP TABLE IF EXISTS core_questionsource;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    "DROP TABLE IF EXISTS core_questiontypeconfig;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    "DROP TABLE IF EXISTS core_detailedblueprinttemplate;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
