# Generated by Django 5.2.14 on 2026-06-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_alter_detailedblueprinttemplate_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="unit",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
