# Generated by Django 5.2.14 on 2026-06-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_material_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionpaper",
            name="status_detail",
            field=models.TextField(blank=True, default=""),
        ),
    ]
