# Generated by Django 5.2.14 on 2026-06-23 21:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_questionpaper_status_detail"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UsageEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paper_id", models.IntegerField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("generate", "Generate"),
                            ("regenerate", "Regenerate"),
                            ("rerender", "Re-render"),
                            ("edit", "AI Edit"),
                            ("pattern", "Pattern"),
                        ],
                        default="generate",
                        max_length=20,
                    ),
                ),
                ("input_tokens", models.BigIntegerField(default=0)),
                ("output_tokens", models.BigIntegerField(default=0)),
                (
                    "cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_events",
                        to="core.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="core_usagee_user_id_de9274_idx",
                    ),
                    models.Index(
                        fields=["school", "created_at"],
                        name="core_usagee_school__d9ab88_idx",
                    ),
                ],
            },
        ),
    ]
