# Generated by Django 5.2.14 on 2026-06-26 19:34

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_enable_pgvector"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(max_length=32)),
                ("subject", models.CharField(max_length=64)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("material_type", models.CharField(default="textbook", max_length=50)),
                ("chunk_index", models.IntegerField(default=0)),
                ("content", models.TextField()),
                ("provider", models.CharField(default="local", max_length=20)),
                (
                    "embedding_local",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=768, null=True
                    ),
                ),
                (
                    "embedding_or",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=2048, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="core.material",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="core.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChunkChapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit", models.CharField(max_length=255)),
                (
                    "chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapter_links",
                        to="core.materialchunk",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="materialchunk",
            index=models.Index(
                fields=["class_name", "subject", "school"], name="chunk_css_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="materialchunk",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["embedding_local"],
                m=16,
                name="chunk_emb_local_hnsw",
                opclasses=["vector_cosine_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="chunkchapter",
            index=models.Index(fields=["unit"], name="chunkchapter_unit_idx"),
        ),
        migrations.AddConstraint(
            model_name="chunkchapter",
            constraint=models.UniqueConstraint(
                fields=("chunk", "unit"), name="uniq_chunk_unit"
            ),
        ),
    ]
