# Generated by Django 5.2.14 on 2026-06-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_materialchunk_chunkchapter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("shared", "Shared (global / superadmin)"),
                    ("private", "Private to school"),
                    ("institutional", "Shared across all schools"),
                ],
                db_index=True,
                default="private",
                max_length=20,
            ),
        ),
    ]
