# Generated by Django 4.2.30 on 2026-06-29 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0029_material_visibility"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolVectorLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vector_links_in",
                        to="core.school",
                    ),
                ),
                (
                    "viewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vector_links_out",
                        to="core.school",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="schoolvectorlink",
            constraint=models.UniqueConstraint(
                fields=("viewer", "source"), name="uniq_school_vector_link"
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolvectorlink",
            constraint=models.CheckConstraint(
                check=models.Q(("viewer", models.F("source")), _negated=True),
                name="no_self_vector_link",
            ),
        ),
    ]
