# Generated by Django 4.2.30 on 2026-07-01 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0030_schoolvectorlink_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("shared", "Shared (global / superadmin)"),
                    ("private", "Private to school"),
                    ("institutional", "Shared across all schools"),
                    ("store", "Vector store (allocated schools only)"),
                ],
                db_index=True,
                default="private",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="VectorStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schools",
                    models.ManyToManyField(
                        blank=True, related_name="vector_stores", to="core.school"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="material",
            name="vector_store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="materials",
                to="core.vectorstore",
            ),
        ),
    ]
