# Generated by Django 4.2.30 on 2026-07-01 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0031_alter_material_visibility_vectorstore_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookContents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(max_length=10)),
                ("subject", models.CharField(max_length=100)),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("units", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_contents",
                        to="core.school",
                    ),
                ),
            ],
            options={
                "ordering": ["class_name", "subject"],
            },
        ),
    ]
