# Generated by Django 4.2.30 on 2026-07-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_bookcontents"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionpaper",
            name="gen_params",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
