# Generated by Django 4.2.30 on 2026-07-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_systemnotification_schools"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemnotification",
            name="animation_interval",
            field=models.IntegerField(
                default=10,
                help_text="Scroll animation interval in seconds (higher = slower)",
            ),
        ),
    ]
