# Generated by Django 5.0.6 on 2026-07-13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_systemnotification_animation_interval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('generating', 'Generating'), ('done', 'Done'), ('failed', 'Failed'), ('stale', 'Stale')], default='queued', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('source_revision_hash', models.CharField(blank=True, default='', max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('cost', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('input_tokens', models.BigIntegerField(default=0)),
                ('output_tokens', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer_key', to='core.questionpaper')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_answer_keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
