# Generated by Django 4.2.30 on 2026-07-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_answerkey_usage_event_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usageevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("generate", "Generate"),
                    ("regenerate", "Regenerate"),
                    ("rerender", "Re-render"),
                    ("edit", "AI Edit"),
                    ("answer_key", "Answer Key"),
                    ("pattern", "Pattern"),
                ],
                default="generate",
                max_length=20,
            ),
        ),
    ]
