# Generated by Django 4.2.30 on 2026-07-15 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0039_backfill_unicode_chunk_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialchunk",
            name="content_kinds",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="materialchunk",
            name="enriched_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="materialchunk",
            name="garbled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="materialchunk",
            name="kind",
            field=models.CharField(db_index=True, default="body", max_length=16),
        ),
        migrations.AddField(
            model_name="materialchunk",
            name="language",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="usageevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("generate", "Generate"),
                    ("regenerate", "Regenerate"),
                    ("rerender", "Re-render"),
                    ("edit", "AI Edit"),
                    ("answer_key", "Answer Key"),
                    ("pattern", "Pattern"),
                    ("enrichment", "Chunk Enrichment"),
                ],
                default="generate",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="EnrichmentRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("force", models.BooleanField(default=False)),
                ("total_groups", models.IntegerField(default=0)),
                ("done_groups", models.IntegerField(default=0)),
                ("failed_groups", models.IntegerField(default=0)),
                ("chunks_labeled", models.IntegerField(default=0)),
                ("summaries_created", models.IntegerField(default=0)),
                ("garbled_found", models.IntegerField(default=0)),
                ("input_tokens", models.BigIntegerField(default=0)),
                ("output_tokens", models.BigIntegerField(default=0)),
                (
                    "cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                ("error_samples", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
