# Generated by Django 4.2.30 on 2026-07-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_materialchunk_content_kinds_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialchunk",
            name="content_clean",
            field=models.TextField(blank=True, default=""),
        ),
    ]
