# Generated by Django 4.2.30 on 2026-07-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_materialchunk_content_clean"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrichmentrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "Running"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                    ("stopped", "Stopped"),
                ],
                default="running",
                max_length=20,
            ),
        ),
    ]
