# Generated by Django 4.2.30 on 2026-07-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_alter_enrichmentrun_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrichmentrun",
            name="drained_groups",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="enrichmentrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "Running"),
                    ("stopping", "Stopping"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                    ("stopped", "Stopped"),
                ],
                default="running",
                max_length=20,
            ),
        ),
    ]
