# Generated by Django 4.2.30 on 2026-07-17 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_enrichmentrun_drained_groups_and_more"),
        ("core", "0044_school_billing_period_over"),
    ]

    operations = []
