# Generated by Django 4.2.30 on 2026-07-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_merge_20260717_1007"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChapterInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(max_length=50)),
                ("subject", models.CharField(max_length=100)),
                ("unit", models.CharField(max_length=255)),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("prose", "Prose"),
                            ("poem", "Poem"),
                            ("drama", "Drama"),
                            ("supplementary", "Supplementary"),
                            ("grammar", "Grammar"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("classified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["class_name", "subject"],
                        name="chapterinfo_cls_subj_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="chapterinfo",
            constraint=models.UniqueConstraint(
                fields=("class_name", "subject", "unit"), name="uniq_chapterinfo_key"
            ),
        ),
    ]
