# Generated by Django 4.2.30 on 2026-07-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_userprofile_last_seen_directmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="total_images_generated",
            field=models.BigIntegerField(default=0),
        ),
    ]
