# Generated by Django 4.2.30 on 2026-08-18 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_school_disable_image_generation"),
    ]

    operations = [
        migrations.AddField(
            model_name="examblueprint",
            name="name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="examblueprint",
            name="pattern",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blueprints",
                to="core.exampattern",
            ),
        ),
        migrations.AddField(
            model_name="examblueprint",
            name="unit_map",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
