# Generated by Django 4.2.30 on 2026-08-19 04:04

from django.db import migrations, models


def move_sqp_patterns_to_their_own_source(apps, schema_editor):
    """Reclassify the SQP-derived patterns from 'cbse_official' to 'cbse_sqp'.

    They were imported as cbse_official so they would replace the hand-seeded board patterns in
    place, but sharing that source is dangerous: `seed_cbse_patterns --force` DELETES every
    cbse_official row, and `update_cbse_patterns_task` regenerates them from the LLM — either
    would silently destroy a faithful question-by-question replica of the official sample paper.
    Their own source also makes "reusable for any class or subject" an exact filter in the
    template picker instead of a guess.

    Identified by the presence of `question_slots`, the per-question structure only the importer
    produces; the hand-written seeds in core/data/cbse_patterns.py are aggregates and stay put.
    """
    ExamPattern = apps.get_model("core", "ExamPattern")
    for pattern in ExamPattern.objects.filter(pattern_source="cbse_official"):
        sections = pattern.sections
        slot_authored = isinstance(sections, list) and any(
            isinstance(s, dict) and s.get("question_slots") for s in sections)
        if slot_authored:
            pattern.pattern_source = "cbse_sqp"
            pattern.save(update_fields=["pattern_source"])


def move_back(apps, schema_editor):
    ExamPattern = apps.get_model("core", "ExamPattern")
    ExamPattern.objects.filter(pattern_source="cbse_sqp").update(pattern_source="cbse_official")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_sqp_patterns_drop_class_from_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exampattern",
            name="pattern_source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Creation"),
                    ("ai_generated", "AI Generated"),
                    ("imported", "Imported"),
                    ("cbse_official", "CBSE Official"),
                    ("cbse_sqp", "CBSE Sample Paper"),
                    ("one_mark_test", "One Mark Test"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
            migrations.RunPython(move_sqp_patterns_to_their_own_source, move_back),
    ]
