# Generated by Django 4.2.30 on 2026-08-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_sqp_patterns_own_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="exampattern",
            name="class_max",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exampattern",
            name="class_min",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
