# Generated by Django 4.2.30 on 2026-08-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_exampattern_class_band"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionpaper",
            name="creative_ratio",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
