# Generated by Django 5.0.1 on 2025-09-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_examblueprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
